/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram-webhook'
import { Route as PaymentOrderIdRouteImport } from './routes/payment.$orderId'
import { Route as ApiPublicAdvanceDeliveriesRouteImport } from './routes/api/public/advance-deliveries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram-webhook',
  path: '/api/telegram-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOrderIdRoute = PaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdvanceDeliveriesRoute =
  ApiPublicAdvanceDeliveriesRouteImport.update({
    id: '/api/public/advance-deliveries',
    path: '/api/public/advance-deliveries',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/missions': typeof MissionsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/stars': typeof StarsRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/api/public/advance-deliveries': typeof ApiPublicAdvanceDeliveriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/missions': typeof MissionsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/stars': typeof StarsRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/api/public/advance-deliveries': typeof ApiPublicAdvanceDeliveriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/missions': typeof MissionsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/stars': typeof StarsRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/api/public/advance-deliveries': typeof ApiPublicAdvanceDeliveriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/missions'
    | '/orders'
    | '/points'
    | '/premium'
    | '/profile'
    | '/referral'
    | '/stars'
    | '/api/telegram-webhook'
    | '/payment/$orderId'
    | '/api/public/advance-deliveries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/missions'
    | '/orders'
    | '/points'
    | '/premium'
    | '/profile'
    | '/referral'
    | '/stars'
    | '/api/telegram-webhook'
    | '/payment/$orderId'
    | '/api/public/advance-deliveries'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/missions'
    | '/orders'
    | '/points'
    | '/premium'
    | '/profile'
    | '/referral'
    | '/stars'
    | '/api/telegram-webhook'
    | '/payment/$orderId'
    | '/api/public/advance-deliveries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MissionsRoute: typeof MissionsRoute
  OrdersRoute: typeof OrdersRoute
  PointsRoute: typeof PointsRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  StarsRoute: typeof StarsRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
  ApiPublicAdvanceDeliveriesRoute: typeof ApiPublicAdvanceDeliveriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-webhook': {
      id: '/api/telegram-webhook'
      path: '/api/telegram-webhook'
      fullPath: '/api/telegram-webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/advance-deliveries': {
      id: '/api/public/advance-deliveries'
      path: '/api/public/advance-deliveries'
      fullPath: '/api/public/advance-deliveries'
      preLoaderRoute: typeof ApiPublicAdvanceDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MissionsRoute: MissionsRoute,
  OrdersRoute: OrdersRoute,
  PointsRoute: PointsRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  StarsRoute: StarsRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
  ApiPublicAdvanceDeliveriesRoute: ApiPublicAdvanceDeliveriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
